language: generic

jdk:
  - oraclejdk8

env:
  global:
    - ENCRYPTION_LABEL="82f6fcb5a224"
    - DEPLOY_USER="annevankesteren"
    - TITLE="URL Standard"

script:
  - bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
